# This workflow will install Rust dependencies, run tests and lint with a single version of Rust
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: main

on:
    push:
        branches:
            - main
            - develop
        tags:
            - "*"

    pull_request:
        branches:
            - main
            - develop

jobs:
    Test:
        name: Cargo Test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
              with:
                cache-all-crates: "true"
                cache-on-failure: "true"
            - uses: davidB/rust-cargo-make@v1
            - run: cargo make test
    Lint:
        name: Rust Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                components: rustfmt
            - uses: Swatinem/rust-cache@v2
              with:
                cache-all-crates: "true"
                cache-on-failure: "true"
            - uses: davidB/rust-cargo-make@v1
            - run: cargo make lint
